/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as HelpersRouteImport } from './routes/helpers'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpikeSpeakerIdRouteImport } from './routes/spike.speaker-id'
import { Route as ApiTtsVoicesRouteImport } from './routes/api/tts/voices'
import { Route as ApiTtsSaveDesignedVoiceRouteImport } from './routes/api/tts/save-designed-voice'
import { Route as ApiTtsElevenlabsRouteImport } from './routes/api/tts/elevenlabs'
import { Route as ApiTtsDesignPreviewsRouteImport } from './routes/api/tts/design-previews'
import { Route as ApiTtsCartesiaRouteImport } from './routes/api/tts/cartesia'
import { Route as ApiSttScribeTokenRouteImport } from './routes/api/stt/scribe-token'
import { Route as ApiSttElevenlabsRouteImport } from './routes/api/stt/elevenlabs'
import { Route as ApiLlmOpenaiRouteImport } from './routes/api/llm/openai'
import { Route as ApiLlmAnthropicRouteImport } from './routes/api/llm/anthropic'
import { Route as ApiEmbedOpenaiRouteImport } from './routes/api/embed/openai'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpersRoute = HelpersRouteImport.update({
  id: '/helpers',
  path: '/helpers',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpikeSpeakerIdRoute = SpikeSpeakerIdRouteImport.update({
  id: '/spike/speaker-id',
  path: '/spike/speaker-id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsVoicesRoute = ApiTtsVoicesRouteImport.update({
  id: '/api/tts/voices',
  path: '/api/tts/voices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsSaveDesignedVoiceRoute = ApiTtsSaveDesignedVoiceRouteImport.update({
  id: '/api/tts/save-designed-voice',
  path: '/api/tts/save-designed-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsElevenlabsRoute = ApiTtsElevenlabsRouteImport.update({
  id: '/api/tts/elevenlabs',
  path: '/api/tts/elevenlabs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsDesignPreviewsRoute = ApiTtsDesignPreviewsRouteImport.update({
  id: '/api/tts/design-previews',
  path: '/api/tts/design-previews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsCartesiaRoute = ApiTtsCartesiaRouteImport.update({
  id: '/api/tts/cartesia',
  path: '/api/tts/cartesia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttScribeTokenRoute = ApiSttScribeTokenRouteImport.update({
  id: '/api/stt/scribe-token',
  path: '/api/stt/scribe-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttElevenlabsRoute = ApiSttElevenlabsRouteImport.update({
  id: '/api/stt/elevenlabs',
  path: '/api/stt/elevenlabs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmOpenaiRoute = ApiLlmOpenaiRouteImport.update({
  id: '/api/llm/openai',
  path: '/api/llm/openai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmAnthropicRoute = ApiLlmAnthropicRouteImport.update({
  id: '/api/llm/anthropic',
  path: '/api/llm/anthropic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbedOpenaiRoute = ApiEmbedOpenaiRouteImport.update({
  id: '/api/embed/openai',
  path: '/api/embed/openai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/helpers': typeof HelpersRoute
  '/people': typeof PeopleRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/spike/speaker-id': typeof SpikeSpeakerIdRoute
  '/api/embed/openai': typeof ApiEmbedOpenaiRoute
  '/api/llm/anthropic': typeof ApiLlmAnthropicRoute
  '/api/llm/openai': typeof ApiLlmOpenaiRoute
  '/api/stt/elevenlabs': typeof ApiSttElevenlabsRoute
  '/api/stt/scribe-token': typeof ApiSttScribeTokenRoute
  '/api/tts/cartesia': typeof ApiTtsCartesiaRoute
  '/api/tts/design-previews': typeof ApiTtsDesignPreviewsRoute
  '/api/tts/elevenlabs': typeof ApiTtsElevenlabsRoute
  '/api/tts/save-designed-voice': typeof ApiTtsSaveDesignedVoiceRoute
  '/api/tts/voices': typeof ApiTtsVoicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/helpers': typeof HelpersRoute
  '/people': typeof PeopleRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/spike/speaker-id': typeof SpikeSpeakerIdRoute
  '/api/embed/openai': typeof ApiEmbedOpenaiRoute
  '/api/llm/anthropic': typeof ApiLlmAnthropicRoute
  '/api/llm/openai': typeof ApiLlmOpenaiRoute
  '/api/stt/elevenlabs': typeof ApiSttElevenlabsRoute
  '/api/stt/scribe-token': typeof ApiSttScribeTokenRoute
  '/api/tts/cartesia': typeof ApiTtsCartesiaRoute
  '/api/tts/design-previews': typeof ApiTtsDesignPreviewsRoute
  '/api/tts/elevenlabs': typeof ApiTtsElevenlabsRoute
  '/api/tts/save-designed-voice': typeof ApiTtsSaveDesignedVoiceRoute
  '/api/tts/voices': typeof ApiTtsVoicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/helpers': typeof HelpersRoute
  '/people': typeof PeopleRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/spike/speaker-id': typeof SpikeSpeakerIdRoute
  '/api/embed/openai': typeof ApiEmbedOpenaiRoute
  '/api/llm/anthropic': typeof ApiLlmAnthropicRoute
  '/api/llm/openai': typeof ApiLlmOpenaiRoute
  '/api/stt/elevenlabs': typeof ApiSttElevenlabsRoute
  '/api/stt/scribe-token': typeof ApiSttScribeTokenRoute
  '/api/tts/cartesia': typeof ApiTtsCartesiaRoute
  '/api/tts/design-previews': typeof ApiTtsDesignPreviewsRoute
  '/api/tts/elevenlabs': typeof ApiTtsElevenlabsRoute
  '/api/tts/save-designed-voice': typeof ApiTtsSaveDesignedVoiceRoute
  '/api/tts/voices': typeof ApiTtsVoicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/helpers'
    | '/people'
    | '/recent'
    | '/settings'
    | '/spike/speaker-id'
    | '/api/embed/openai'
    | '/api/llm/anthropic'
    | '/api/llm/openai'
    | '/api/stt/elevenlabs'
    | '/api/stt/scribe-token'
    | '/api/tts/cartesia'
    | '/api/tts/design-previews'
    | '/api/tts/elevenlabs'
    | '/api/tts/save-designed-voice'
    | '/api/tts/voices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/helpers'
    | '/people'
    | '/recent'
    | '/settings'
    | '/spike/speaker-id'
    | '/api/embed/openai'
    | '/api/llm/anthropic'
    | '/api/llm/openai'
    | '/api/stt/elevenlabs'
    | '/api/stt/scribe-token'
    | '/api/tts/cartesia'
    | '/api/tts/design-previews'
    | '/api/tts/elevenlabs'
    | '/api/tts/save-designed-voice'
    | '/api/tts/voices'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/helpers'
    | '/people'
    | '/recent'
    | '/settings'
    | '/spike/speaker-id'
    | '/api/embed/openai'
    | '/api/llm/anthropic'
    | '/api/llm/openai'
    | '/api/stt/elevenlabs'
    | '/api/stt/scribe-token'
    | '/api/tts/cartesia'
    | '/api/tts/design-previews'
    | '/api/tts/elevenlabs'
    | '/api/tts/save-designed-voice'
    | '/api/tts/voices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  HelpersRoute: typeof HelpersRoute
  PeopleRoute: typeof PeopleRoute
  RecentRoute: typeof RecentRoute
  SettingsRoute: typeof SettingsRoute
  SpikeSpeakerIdRoute: typeof SpikeSpeakerIdRoute
  ApiEmbedOpenaiRoute: typeof ApiEmbedOpenaiRoute
  ApiLlmAnthropicRoute: typeof ApiLlmAnthropicRoute
  ApiLlmOpenaiRoute: typeof ApiLlmOpenaiRoute
  ApiSttElevenlabsRoute: typeof ApiSttElevenlabsRoute
  ApiSttScribeTokenRoute: typeof ApiSttScribeTokenRoute
  ApiTtsCartesiaRoute: typeof ApiTtsCartesiaRoute
  ApiTtsDesignPreviewsRoute: typeof ApiTtsDesignPreviewsRoute
  ApiTtsElevenlabsRoute: typeof ApiTtsElevenlabsRoute
  ApiTtsSaveDesignedVoiceRoute: typeof ApiTtsSaveDesignedVoiceRoute
  ApiTtsVoicesRoute: typeof ApiTtsVoicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpers': {
      id: '/helpers'
      path: '/helpers'
      fullPath: '/helpers'
      preLoaderRoute: typeof HelpersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spike/speaker-id': {
      id: '/spike/speaker-id'
      path: '/spike/speaker-id'
      fullPath: '/spike/speaker-id'
      preLoaderRoute: typeof SpikeSpeakerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts/voices': {
      id: '/api/tts/voices'
      path: '/api/tts/voices'
      fullPath: '/api/tts/voices'
      preLoaderRoute: typeof ApiTtsVoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts/save-designed-voice': {
      id: '/api/tts/save-designed-voice'
      path: '/api/tts/save-designed-voice'
      fullPath: '/api/tts/save-designed-voice'
      preLoaderRoute: typeof ApiTtsSaveDesignedVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts/elevenlabs': {
      id: '/api/tts/elevenlabs'
      path: '/api/tts/elevenlabs'
      fullPath: '/api/tts/elevenlabs'
      preLoaderRoute: typeof ApiTtsElevenlabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts/design-previews': {
      id: '/api/tts/design-previews'
      path: '/api/tts/design-previews'
      fullPath: '/api/tts/design-previews'
      preLoaderRoute: typeof ApiTtsDesignPreviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts/cartesia': {
      id: '/api/tts/cartesia'
      path: '/api/tts/cartesia'
      fullPath: '/api/tts/cartesia'
      preLoaderRoute: typeof ApiTtsCartesiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt/scribe-token': {
      id: '/api/stt/scribe-token'
      path: '/api/stt/scribe-token'
      fullPath: '/api/stt/scribe-token'
      preLoaderRoute: typeof ApiSttScribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt/elevenlabs': {
      id: '/api/stt/elevenlabs'
      path: '/api/stt/elevenlabs'
      fullPath: '/api/stt/elevenlabs'
      preLoaderRoute: typeof ApiSttElevenlabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm/openai': {
      id: '/api/llm/openai'
      path: '/api/llm/openai'
      fullPath: '/api/llm/openai'
      preLoaderRoute: typeof ApiLlmOpenaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm/anthropic': {
      id: '/api/llm/anthropic'
      path: '/api/llm/anthropic'
      fullPath: '/api/llm/anthropic'
      preLoaderRoute: typeof ApiLlmAnthropicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embed/openai': {
      id: '/api/embed/openai'
      path: '/api/embed/openai'
      fullPath: '/api/embed/openai'
      preLoaderRoute: typeof ApiEmbedOpenaiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  HelpersRoute: HelpersRoute,
  PeopleRoute: PeopleRoute,
  RecentRoute: RecentRoute,
  SettingsRoute: SettingsRoute,
  SpikeSpeakerIdRoute: SpikeSpeakerIdRoute,
  ApiEmbedOpenaiRoute: ApiEmbedOpenaiRoute,
  ApiLlmAnthropicRoute: ApiLlmAnthropicRoute,
  ApiLlmOpenaiRoute: ApiLlmOpenaiRoute,
  ApiSttElevenlabsRoute: ApiSttElevenlabsRoute,
  ApiSttScribeTokenRoute: ApiSttScribeTokenRoute,
  ApiTtsCartesiaRoute: ApiTtsCartesiaRoute,
  ApiTtsDesignPreviewsRoute: ApiTtsDesignPreviewsRoute,
  ApiTtsElevenlabsRoute: ApiTtsElevenlabsRoute,
  ApiTtsSaveDesignedVoiceRoute: ApiTtsSaveDesignedVoiceRoute,
  ApiTtsVoicesRoute: ApiTtsVoicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
