/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as HelpersRouteImport } from './routes/helpers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversationNewRouteImport } from './routes/conversation.new'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpersRoute = HelpersRouteImport.update({
  id: '/helpers',
  path: '/helpers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationNewRoute = ConversationNewRouteImport.update({
  id: '/conversation/new',
  path: '/conversation/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/helpers': typeof HelpersRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/conversation/new': typeof ConversationNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/helpers': typeof HelpersRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/conversation/new': typeof ConversationNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/helpers': typeof HelpersRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/conversation/new': typeof ConversationNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/helpers' | '/recent' | '/settings' | '/conversation/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/helpers' | '/recent' | '/settings' | '/conversation/new'
  id:
    | '__root__'
    | '/'
    | '/helpers'
    | '/recent'
    | '/settings'
    | '/conversation/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpersRoute: typeof HelpersRoute
  RecentRoute: typeof RecentRoute
  SettingsRoute: typeof SettingsRoute
  ConversationNewRoute: typeof ConversationNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpers': {
      id: '/helpers'
      path: '/helpers'
      fullPath: '/helpers'
      preLoaderRoute: typeof HelpersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/new': {
      id: '/conversation/new'
      path: '/conversation/new'
      fullPath: '/conversation/new'
      preLoaderRoute: typeof ConversationNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpersRoute: HelpersRoute,
  RecentRoute: RecentRoute,
  SettingsRoute: SettingsRoute,
  ConversationNewRoute: ConversationNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
