/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as HelpersRouteImport } from './routes/helpers'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpikeSpeakerIdRouteImport } from './routes/spike.speaker-id'
import { Route as ApiLlmAnthropicRouteImport } from './routes/api/llm/anthropic'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpersRoute = HelpersRouteImport.update({
  id: '/helpers',
  path: '/helpers',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpikeSpeakerIdRoute = SpikeSpeakerIdRouteImport.update({
  id: '/spike/speaker-id',
  path: '/spike/speaker-id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmAnthropicRoute = ApiLlmAnthropicRouteImport.update({
  id: '/api/llm/anthropic',
  path: '/api/llm/anthropic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/helpers': typeof HelpersRoute
  '/people': typeof PeopleRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/spike/speaker-id': typeof SpikeSpeakerIdRoute
  '/api/llm/anthropic': typeof ApiLlmAnthropicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/helpers': typeof HelpersRoute
  '/people': typeof PeopleRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/spike/speaker-id': typeof SpikeSpeakerIdRoute
  '/api/llm/anthropic': typeof ApiLlmAnthropicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/helpers': typeof HelpersRoute
  '/people': typeof PeopleRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/spike/speaker-id': typeof SpikeSpeakerIdRoute
  '/api/llm/anthropic': typeof ApiLlmAnthropicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/helpers'
    | '/people'
    | '/recent'
    | '/settings'
    | '/spike/speaker-id'
    | '/api/llm/anthropic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/helpers'
    | '/people'
    | '/recent'
    | '/settings'
    | '/spike/speaker-id'
    | '/api/llm/anthropic'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/helpers'
    | '/people'
    | '/recent'
    | '/settings'
    | '/spike/speaker-id'
    | '/api/llm/anthropic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  HelpersRoute: typeof HelpersRoute
  PeopleRoute: typeof PeopleRoute
  RecentRoute: typeof RecentRoute
  SettingsRoute: typeof SettingsRoute
  SpikeSpeakerIdRoute: typeof SpikeSpeakerIdRoute
  ApiLlmAnthropicRoute: typeof ApiLlmAnthropicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpers': {
      id: '/helpers'
      path: '/helpers'
      fullPath: '/helpers'
      preLoaderRoute: typeof HelpersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spike/speaker-id': {
      id: '/spike/speaker-id'
      path: '/spike/speaker-id'
      fullPath: '/spike/speaker-id'
      preLoaderRoute: typeof SpikeSpeakerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm/anthropic': {
      id: '/api/llm/anthropic'
      path: '/api/llm/anthropic'
      fullPath: '/api/llm/anthropic'
      preLoaderRoute: typeof ApiLlmAnthropicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  HelpersRoute: HelpersRoute,
  PeopleRoute: PeopleRoute,
  RecentRoute: RecentRoute,
  SettingsRoute: SettingsRoute,
  SpikeSpeakerIdRoute: SpikeSpeakerIdRoute,
  ApiLlmAnthropicRoute: ApiLlmAnthropicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
